# Generated by Django 4.2 on 2023-07-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_nofification_delete_videostatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nofification',
            new_name='Notification',
        ),
    ]
