# Generated by Django 4.2 on 2023-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_nofification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Seen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
