# Generated by Django 4.2 on 2023-07-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_notification_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
