# Generated by Django 4.2 on 2023-10-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_videostatus_userpreference_baseroomparticipants'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
